MXOnline/urls.py
from django.contrib import admin
from django.urls import path
import xadmin
from apps.users import views
from django.views.generic import  TemplateView
from apps.users.views import LoginView
from apps.organizations.views import OrgView
from apps.operations.views import IndexView

from django.conf.urls import url
from django.conf.urls import include
from django.views.static import serve
from MXOnline.settings import MEDIA_ROOT
from apps.courses.views import CourseLessonView
from apps.users.views import LoginView, LogoutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    # path('', views.index),
    # zheyang就不用定义视图函数
    # path('',TemplateView.as_view(template_name="index.html"),name='index'),
    path('',IndexView.as_view(),name='index'),

    # path('courselist/',TemplateView.as_view(template_name="course-list.html"),name='course-list'),
    # path('login/',LoginView.as_view())
    path('login/',LoginView.as_view(),name='login'),

    #     配置机构展示列表
    # path('orglist/', OrgView.as_view(), name='org_list'),

    # 授课机构相关操作
    url(r'^org/', include(('apps.organizations.urls',"organizations") , namespace='org')),
    # 配置课程相关页面
    url(r'^course/', include(('apps.courses.urls',"courses") , namespace='course')),
    # 配置上传文件的访问url
    url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),
    # 用户相关操作
    url(r'^op/', include(('apps.operations.urls', "operations"), namespace="op")),
    path('logout/', LogoutView.as_view(), name="logout"),

    url(r'^users/', include(('apps.users.urls', 'users'), namespace='users')),
]

apps/courses/urls.py
from django.conf.urls import url
from apps.courses.views import CourseListView,CourseDetailView,CourseLessonView,CourseCommentsView,VideoView

urlpatterns = [
    url(r'^list/$',CourseListView.as_view(), name="list"),
    # url(r'^detail/$',CourseListView.as_view(), name="detail"),
    url(r'^(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="detail"),
    url(r'^(?P<course_id>\d+)/lesson$', CourseLessonView.as_view(), name="lesson"),
    url(r'^(?P<course_id>\d+)/comments/$', CourseCommentsView.as_view(), name="comments"),
    url(r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)$', VideoView.as_view(), name="video"),
]

apps/operations/urls.py
from django.conf.urls import url
from apps.operations.views import AddFavView,CommentView
urlpatterns = [
    url(r'^fav/$', AddFavView.as_view(), name="fav"),
    url(r'^comment/$', CommentView.as_view(), name="comment"),
]

apps/organizations/urls.py
from django.conf.urls import url
from apps.organizations.views import OrgView
from apps.organizations.views import OrgView, AddAsk,TeacherListView,TeacherDetailView

urlpatterns = [
    url(r'^list/$',OrgView.as_view(), name="list"),
    url(r'^add_ask/$',AddAsk.as_view(), name="add_ask"),
    # 教师相关
    url(r'^teachers/$',TeacherListView.as_view(), name="teachers"),
    url(r'^teachers/(?P<teacher_id>\d+)$',TeacherDetailView.as_view(), name="teacher_detail"),
]

apps/users/urls.py
from django.conf.urls import url
from apps.organizations.views import OrgView, AddAsk, TeacherListView, TeacherDetailView
from apps.users.views import UserInfoView,MyFavOrgView, MyFavCourseView, MyFavTeacherView,ChangePwdView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name='info'),
    # url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),
    url(r'^mycourse/$',login_required(TemplateView.as_view(template_name='usercenter-mycourse.html'), login_url='/login/'),{"current_page": "mycourse"}, name='mycourse'),
    url(r'^myfavorg/$', MyFavOrgView.as_view(), name='myfavorg'),
    url(r'^myfav_teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),
    url(r'^myfav_course/$', MyFavCourseView.as_view(), name='myfav_course'),
    url(r'^update/pwd/$', ChangePwdView.as_view(), name='update_pwd'),

]

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}课程章节信息 - 慕学在线网{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}">
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:list' %}">公开课程</a>></li>
                    <li><a href="">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn" href="{% url 'course:lesson' course.id %}"><span>章节</span></a>
                            </li>
                            <li><a id="commentOn" class="active" href="{% url 'course:comments' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for comment in comments %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ comment.user.image.url }}'
                                                               width='40' height='40'/></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{% if comment.user.nick_name %}{{ comment.user.nick_name }}{% else %}{{ comment.user.username }}{% endif %}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                            <h4>资料下载</h4>
                            <ul class="downlist">
                                {% for resource in course_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ resource.file.url }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="box mb40">
                            <h4>讲师提示</h4>
                            <div class="teacher-info">
                                <a href="/u/315464/courses?sort=publish" target="_blank">
                                    <img src='{{ course.teacher.image.url }}' width='80' height='80'/>
                                </a>
                                <span class="tit">
                                    <a href="{{ course.teacher.name }}" target="_blank">bobby</a>
                                </span>

                                <span class="job">{{ course.teacher.work_position }}</span>
                            </div>
                            <div class="course-info-tip">
                                <dl class="first">
                                    <dt>课程须知</dt>
                                    <dd class="autowrap">{{ course.youneed_know }}</dd>
                                </dl>
                                <dl>
                                    <dt>老师告诉你能学到什么？</dt>
                                    <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                </dl>
                            </div>
                        </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                     style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        {% for course in related_courses %}
                                            <li class="curr">
                                                <a href="{% url 'course:detail' course.id %}" target="_blank">
                                                    <img src="{{ course.image.url }}"
                                                         alt="{{ course.name }}">
                                                    <span class="name autowrap">{{ course.name }}</span>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                                     alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        //添加评论
        $(document).ready(function () {
            $('#js-pl-submit').on('click', function () {
                var comments = $("#js-pl-textarea").val()
                if (comments == "") {
                    alert("评论不能为空")
                    return
                }
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'op:comment' %}",
                    data: {'course': {{ course.id }}, 'comments': comments},
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status == 'fail') {
                            if (data.msg == '用户未登录') {
                                window.location.href = "{% url 'login' %}";
                            } else {
                                alert(data.msg)
                            }

                        } else if (data.status == 'success') {
                            window.location.reload();//刷新当前页面.
                        }
                    },
                });
            });
        });

    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

<!--crumbs start-->
{% block content %}
<div class="banner">
    <div class="wp">
        <div class="fl">
            <div class="imgslide">
                <ul class="imgs">
                    {% for banner in banners %}
                    <li>
                        <a href="{{ banner.url }}">
                            <img width="1200" height="478"
                                 src="{{ banner.image.url }}"/>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>

    </div>


</div>
<!--banner end-->
<!--feature start-->
<section>
    <div class="wp">
        <ul class="feature">
            <li class="feature1">
                <img class="pic" src="/static/images/feature1.png"/>
                <p class="center">专业权威</p>
            </li>
            <li class="feature2">
                <img class="pic" src="/static/images/feature2.png"/>
                <p class="center">课程最新</p>
            </li>
            <li class="feature3">
                <img class="pic" src="/static/images/feature3.png"/>
                <p class="center">名师授课</p>
            </li>
            <li class="feature4">
                <img class="pic" src="/static/images/feature4.png"/>
                <p class="center">数据真实</p>
            </li>
        </ul>
    </div>
</section>
<!--feature end-->
<!--module1 start-->
<section>
    <div class="module">
        <div class="wp">
            <h1>公开课程</h1>
            <div class="module1 eachmod">
                <div class="module1_1 left">
                    <img width="228" height="614" src="/static/images/module3_1.jpg"/>
                    <p class="fisrt_word">名师授课<br/>专业权威</p>
                    <a class="more" href="{% url 'course:list' %}">查看更多课程 ></a>
                </div>
                <div class="right group_list">
                    <div class="module1_2 box">
                        <div class="imgslide2">
                            <ul class="imgs">
                                {% for banner_course in banner_courses %}
                                <li>
                                    <a href="{% url 'course:detail' banner_course.id %}">
                                        <img width="470" height="300"
                                             src="{{ banner_course.image.url }}"/>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="unslider-arrow2 prev"></div>
                        <div class="unslider-arrow2 next"></div>
                    </div>

                    {% for course in  courses %}
                    <div class="module1_{{ forloop.counter| add:2 }} box">
                        <a href="{% url 'course:detail' course.id %}">
                            <img width="233" height="190" src="{{ course.image.url }}"/>
                        </a>
                        <div class="des">
                            <a href="course-detail.html">
                                <h2 title="{{ course.name }}">{{ course.name|slice:'14'}}</h2>
                            </a>
                            <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                            <span class="fr">学习人数：{{ course.students }}</span>
                        </div>
                        <div class="bottom">
                            <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                            <span class="star fr">{{ course.fav_nums }}</span>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="module greybg">
        <div class="wp">
            <h1>课程机构</h1>
            <div class="module3 eachmod">
                <div class="module3_1 left">
                    <img width="228" height="463" src="/static/images/module3_1.jpg"/>
                    <p class="fisrt_word">名校来袭<br/>权威认证</p>
                    <a class="more" href="{% url 'org:list'%}">查看更多机构 ></a>
                </div>
                <div class="right">
                    <ul>
                        {% for org in course_orgs %}
                        <li class="">
                            <a href="#">
                                <div class="company">
                                    <img width="184" height="100" src="{{ org.image.url }}"/>
                                    <div class="score">
                                        <div class="circle">
                                            <h2>{{ org.tag }}</h2>
                                        </div>
                                    </div>
                                </div>
                                <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


{%  block custom_js %}
<script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter-base.html' %}
{% block title %}个人信息- 慕学在线网{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="index.html">首页</a>></li>
            <li><a href="/user/home/">个人中心</a>></li>
            <li>个人信息</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_form %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的课程</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="companycenter">
                <div class="group_list brief">
                    {% for user_course in user.usercourse_set.all %}
                      <div class="module1_5 box">
{#                        <a href="{% url 'course:detail' user_course.cousrse.id %}">#}
                        <a href="#">
                            <img width="214" height="190" class="scrollLoading"
                                 src="{{user_course.course.image.url}}"/>
                        </a>
                        <div class="des">
                            <a href="course-detail.html"><h2>{{user_course.course.name}}</h2></a>
                            <span class="fl">课时：<i class="key">{{user_course.course.learn_times}}</i></span>
                            <span class="fr">学习人数：{{user_course.course.students}}</span>
                        </div>
                             <div class="bottom">
                            <span class="fl">{{user_course.course.course_org.name}}</span>
                            <span class="star fr  notlogin" data-favid="15">{{user_course.course.fav_nums}}</span>
                        </div>
                    </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
	</div>
{% endblock %}